# -*- coding: utf-8 -*-
"""MeuPlanoIA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jfb2B-xeMXEdSUGpn-kdFqFLp0P7_gU9
"""

# Célula 1: Instalar bibliotecas
!pip install -q google-generativeai
!pip install -q gradio

# Célula 2: Importar bibliotecas e configurar a API Key
import os
import google.generativeai as genai
import json
import re
from datetime import datetime
import gradio as gr
import dateutil.relativedelta

os.environ['GOOGLE_API_KEY'] = input("Digite sua chave da API Google Gemini: ")
GOOGLE_API_KEY = os.environ['GOOGLE_API_KEY']
genai.configure(api_key=GOOGLE_API_KEY)
try:
    generation_config = {
        "candidate_count": 1,
        "temperature": 0.7,
    }
    safety_settings = {
        'HATE': 'BLOCK_NONE',
        'HARASSMENT': 'BLOCK_NONE',
        'SEXUAL': 'BLOCK_NONE',
        'DANGEROUS': 'BLOCK_NONE'
    }
    model = genai.GenerativeModel(
        model_name='gemini-1.5-flash',
        generation_config=generation_config,
        safety_settings=safety_settings
    )
    print(f"Modelo '{model.model_name}' configurado.")
except Exception as e:
    print(f"Erro ao configurar a API Key ou o modelo. Erro: {e}")
    model = None

# Utilitários
def parse_tempo_total(tempo_str, horas_semanais):
    semanas = 0
    tempo_str_lower = tempo_str.lower()
    match_semanas = re.search(r'(\d+)\s*semana(s)?', tempo_str_lower)
    if match_semanas:
        semanas = int(match_semanas.group(1))
        return semanas, f"{semanas} semanas ({horas_semanais}h/semana)"
    match_meses = re.search(r'(\d+)\s*m(e|ê)s(es)?', tempo_str_lower)
    if match_meses:
        meses = int(match_meses.group(1))
        hoje = datetime.now()
        data_futura = hoje + dateutil.relativedelta.relativedelta(months=+meses)
        semanas = (data_futura - hoje).days / 7
        return semanas, f"{meses} meses (aprox. {semanas:.1f} semanas, {horas_semanais}h/semana)"
    return None, None

def parse_json_from_gemini(text_response):
    # Remover os backticks e a palavra "json" se estiverem presentes
    text_response = text_response.strip()
    if text_response.startswith("```json"):
        text_response = text_response[len("```json"):].strip()
    elif text_response.startswith("```"):
        text_response = text_response[len("```"):].strip()
    if text_response.endswith("```"):
        text_response = text_response[:-len("```")].strip()

    # Encontrar o início e o fim do JSON válido usando expressões regulares
    json_start = text_response.find('{')
    json_end = text_response.rfind('}')

    if json_start != -1 and json_end != -1:
        json_str = text_response[json_start:json_end + 1]
        try:
            return json.loads(json_str)
        except json.JSONDecodeError as e:
            print(f"Erro ao decodificar JSON: {e}")
            print(f"String JSON com problema: {json_str}")
            return None
    else:
        print("JSON inválido encontrado. Retornando None.")
        return None

# Agentes
def agente_planejador_modulos(objetivo_aprendizado, nivel_aluno, horas_semanais, total_semanas, llm_model):
    if not llm_model:
        return None
    prompt = f"""
Você é um especialista em design instrucional e deve planejar os módulos de um curso.
O objetivo de aprendizado do aluno é: {objetivo_aprendizado}
O nível de conhecimento atual do aluno é: {nivel_aluno}
O aluno tem {horas_semanais} horas disponíveis por semana para estudar.
A duração total desejada para o curso é de {total_semanas} semanas.

Com base nessas informações, crie uma lista de módulos para este curso.
Cada módulo deve conter as seguintes informações:
- "nome_modulo": Um nome conciso para o módulo.
- "descricao_modulo": Uma breve descrição do que será aprendido no módulo.
- "semanas_estimadas": O número estimado de semanas necessárias para completar o módulo.

Retorne a resposta em formato JSON, com a seguinte estrutura:
{{
    "modulos": [
        {{
            "nome_modulo": "Nome do Módulo 1",
            "descricao_modulo": "Descrição do Módulo 1",
            "semanas_estimadas": 1,
            "link_recursos": "https://example.com/modulo1"
        }},
        {{
            "nome_modulo": "Nome do Módulo 2",
            "descricao_modulo": "Descrição do Módulo 2",
            "semanas_estimadas": 2,
            "link_recursos": "https://example.com/modulo2"
        }},
        ...
    ]
}}
"""
    try:
        response = llm_model.generate_content(prompt)
        #print("Resposta bruta do Agente Planejador:", response.text)
        resultado = parse_json_from_gemini(response.text)
        return resultado['modulos'] if resultado and 'modulos' in resultado else None
    except Exception as e:
        print(f"Erro no Agente Planejador: {e}")
        return None

def agente_detalhador_modulo(info_modulo, nivel_aluno, recursos_pref, outras_info_aluno,
                             horas_semanais_dedicadas, llm_model, numero_modulo_global, semana_inicio_global):
    if not llm_model:
        return None
    nome_modulo = info_modulo['nome_modulo']
    descricao = info_modulo['descricao_modulo']
    semanas = info_modulo['semanas_estimadas']
    prompt = f"""
Você é um especialista em design instrucional e deve detalhar o conteúdo do módulo:
MÓDULO: {nome_modulo}
DESCRIÇÃO GERAL DO MÓDULO: {descricao}
O nível de conhecimento atual do aluno é: {nivel_aluno}
Os recursos preferenciais do aluno são: {recursos_pref}
Outras informações relevantes sobre o aluno: {outras_info_aluno}
O aluno tem {horas_semanais_dedicadas} horas disponíveis por semana para este módulo.
Este módulo tem uma duração estimada de {semanas} semanas.
A semana de início deste módulo é {semana_inicio_global}.

Com base nessas informações, **planeje o conteúdo de cada uma das {semanas} semanas deste módulo.**
Para cada semana, liste os tópicos a serem estudados e uma estimativa da duração (em horas) para cada tópico, levando em consideração que o aluno tem {horas_semanais_dedicadas} horas por semana para este módulo.
Inclua um link de recurso para cada tópico.

Retorne a resposta em formato JSON, com a seguinte estrutura:
{{
    "semanas": [
        {{
            "semana": {semana_inicio_global} + 1,
            "topicos": [
                {{
                    "nome_topico": "Tópico 1 da Semana 1",
                    "duracao_estimada": 1.5,
                    "link_recurso": "https://example.com/topico1_semana1"
                }},
                {{
                    "nome_topico": "Tópico 2 da Semana 1",
                    "duracao_estimada": 2.0,
                    "link_recurso": "https://example.com/topico2_semana1"
                }}
            ]
        }},
        {{
            "semana": {semana_inicio_global} + 2,
            "topicos": [
                {{
                    "nome_topico": "Tópico 1 da Semana 2",
                    "duracao_estimada": 2.5,
                    "link_recurso": "https://example.com/topico1_semana2"
                }}
            ]
        }},
        ...
    ]
}}
"""
    try:
        response = llm_model.generate_content(prompt)
        print(f"Resposta bruta do Agente Detalhador para '{nome_modulo}':", response.text)
        resultado = parse_json_from_gemini(response.text)
        return resultado['semanas'] if resultado and 'semanas' in resultado else None
    except Exception as e:
        print(f"Erro no Agente Detalhador para '{nome_modulo}': {e}")
        return None

def agente_formatador_plano_final(dados_usuario, lista_modulos, dict_detalhes_modulos, llm_model):
    if not llm_model:
        return None
    info_usuario = f"""
OBJETIVO: {dados_usuario['objetivo_aprendizado']}
NÍVEL: {dados_usuario['nivel_conhecimento']}
TEMPO: {dados_usuario['tempo_disponivel_original_usuario']}
RECURSOS: {dados_usuario['recursos_preferenciais']}
OUTRAS INFORMAÇÕES: {dados_usuario['outras_informacoes']}
"""
    modulos_texto = "\n".join([f"- {m['nome_modulo']} ({m['semanas_estimadas']} semanas)" for m in lista_modulos])
    detalhes_formatado = json.dumps(dict_detalhes_modulos, indent=2)
    prompt = f"""
Você é um especialista em design instrucional e deve formatar o plano de estudos final para o usuário.
INFORMAÇÕES DO USUÁRIO:
{info_usuario}
MÓDULOS:
{modulos_texto}
DETALHES DOS MÓDULOS (em JSON):
{detalhes_formatado}

Formate um plano de estudos detalhado e amigável para o usuário, utilizando as informações acima. Inclua uma introdução motivadora, a lista de módulos com sua duração estimada e, para cada módulo, os tópicos a serem estudados por semana com uma estimativa de tempo. Conclua com uma mensagem de incentivo.
"""
    try:
        response = llm_model.generate_content(prompt)
        return response.text
    except Exception as e:
        print(f"Erro no Agente Formatador: {e}")
        return None

# Função principal MODIFICADA com barra de progresso
def gerar_plano_estudos(objetivo_aprendizado, horas_semanais, duracao_estudo, nivel_conhecimento, recursos_preferenciais, outras_informacoes):
    status = "Preparando..."
    yield status, ""

    dados_usuario = {
        "objetivo_aprendizado": objetivo_aprendizado,
        "horas_semanais": int(horas_semanais),
        "nivel_conhecimento": nivel_conhecimento,
        "recursos_preferenciais": recursos_preferenciais or "Nenhum especificado",
        "outras_informacoes": outras_informacoes or "Nenhuma especificada"
    }
    semanas, descricao_duracao = parse_tempo_total(duracao_estudo, dados_usuario["horas_semanais"])
    dados_usuario["total_semanas"] = semanas
    dados_usuario["tempo_disponivel_original_usuario"] = descricao_duracao

    if not semanas:
        status = "❌ Erro: duração inválida. Use 'X semanas' ou 'Y meses'."
        yield status, ""
        return status, ""

    status = "Gerando módulos..."
    yield status, ""
    lista_modulos = agente_planejador_modulos(
        objetivo_aprendizado, nivel_conhecimento, dados_usuario["horas_semanais"], semanas, model
    )
    if not lista_modulos:
        status = "❌ Erro ao gerar os módulos."
        yield status, ""
        return status, ""

    detalhes = {}
    num_modulos = len(lista_modulos)
    semana_atual = 0
    for idx, modulo in enumerate(lista_modulos):
        status = f"Detalhando módulo '{modulo['nome_modulo']}' ({idx + 1}/{num_modulos})..."
        yield status, ""
        detalhes_modulo = agente_detalhador_modulo(
            modulo, nivel_conhecimento, dados_usuario["recursos_preferenciais"],
            dados_usuario["outras_informacoes"], dados_usuario["horas_semanais"],
            model, idx + 1, semana_atual
        )
        if not detalhes_modulo:
            status = f"❌ Erro ao detalhar o módulo '{modulo['nome_modulo']}'."
            yield status, ""
            return status, ""
        detalhes[modulo['nome_modulo']] = detalhes_modulo
        semana_atual += modulo['semanas_estimadas']

    status = "Formatando plano final..."
    yield status, ""
    plano = agente_formatador_plano_final(dados_usuario, lista_modulos, detalhes, model) # Passando 'detalhes' para a função
    if not plano:
        status = "❌ Erro ao formatar o plano final."
        yield status, ""
        return status, ""

    # Adicionando formatação Markdown e CSS
    plano_formatado = f"""
<style>
body {{
    font-family: Arial, sans-serif;
    line-height: 1.6;
    color: #333;
    margin: 0;
    padding: 0;
}}
h2 {{
    color: #2c3e50;
    font-size: 24px;
    margin-bottom: 20px;
    border-bottom: 2px solid #bdc3c7;
    padding-bottom: 10px;
    display: flex;
    align-items: center;
}}
h2::before {{
    content: '📚';
    margin-right: 10px;
}}
h3 {{
    color: #34495e;
    font-size: 18px;
    margin-top: 25px;
    margin-bottom: 15px;
    display: flex;
    align-items: center;
}}
h3::before {{
    content: '📌';
    margin-right: 10px;
}}
p {{
    color: #555;
    margin-bottom: 15px;
    text-align: justify;
}}
ul {{
    list-style-type: disc;
    padding-left: 20px;
    margin-bottom: 15px;
}}
ul li {{
    margin-bottom: 5px;
}}
ol {{
    list-style-type: decimal;
    padding-left: 20px;
    margin-bottom: 15px;
}}
ol li {{
    margin-bottom: 5px;
}}
.modulo {{
    background-color: #ecf0f1;
    padding: 20px;
    margin-bottom: 20px;
    border-radius: 8px;
    box-shadow: 0 2px 4px rgba(0,0,0,0.1);
}}
.topico {{
    padding: 15px;
    margin-bottom: 10px;
    border-left: 4px solid #3498db;
    background-color: #f9f9f9;
    border-radius: 5px;
    display: flex;
    align-items: center;
}}
.topico::before {{
    content: '💡';
    margin-right: 10px;
}}
.topico h4 {{
    font-size: 16px;
    margin-bottom: 10px;
    color: #2c3e50;
    }}
.tempo_estimado {{
    font-style: italic;
    color: #7f8c8d;
    display: block;
    margin-top: 5px;
}}
table {{
    width: 100%;
    border-collapse: collapse;
    margin-bottom: 20px;
    background-color: white;
    border-radius: 8px;
    box-shadow: 0 2px 4px rgba(0,0,0,0.1);
}}
th, td {{
    border: 1px solid #ddd;
    padding: 12px;
    text-align: left;
}}
th {{
    background-color: #f0f0f0;
    font-weight: bold;
}}
tr:nth-child(even) {{
    background-color: #f9f9f9;
}}
a {{
    color: #3498db;
    text-decoration: none;
}}
a:hover {{
    text-decoration: underline;
}}
.container {{
    max-width: 900px;
    margin: 50px auto;
    padding: 20px;
    background-color: #fff;
    border-radius: 8px;
    box-shadow: 0 2px 4px rgba(0,0,0,0.1);
}}
</style>
"""
    # Adiciona emojis e formatação de tabela
    plano_formatado = f"""<div class="container">
<h2>Plano de Estudos de Python</h2>
<p>
    Bem-vindo ao seu Plano de Estudos de Python! Prepare-se para embarcar em uma jornada fascinante no mundo da programação com Python!
    Este plano de estudos, elaborado especialmente para você, irá guiá-lo através dos conceitos fundamentais da linguagem.
</p>
<h3>Informações do Aluno:</h3>
<ul>
    <li><strong>Objetivo:</strong> {dados_usuario['objetivo_aprendizado']}</li>
    <li><strong>Nível:</strong> {dados_usuario['nivel_conhecimento']}</li>
    <li><strong>Duração:</strong> {dados_usuario['tempo_disponivel_original_usuario']}</li>
    <li><strong>Recursos:</strong> {dados_usuario['recursos_preferenciais']}</li>
    <li><strong>Outras Informações:</strong> {dados_usuario['outras_informacoes']}</li>
</ul>

<h3>Módulos:</h3>
<ol>
"""
    for modulo in lista_modulos:
        plano_formatado += f"""
    <li>
        <h4>{modulo['nome_modulo']} ({modulo['semanas_estimadas']} semanas)</h4>
        <p>{modulo['descricao_modulo']}</p>
"""
        if modulo['nome_modulo'] in detalhes:
            plano_formatado += "<table><thead><tr><th>Semana</th><th>Tópico</th><th>Duração Estimada</th><th>Link</th></tr></thead><tbody>"
            for semana in detalhes[modulo['nome_modulo']]:
                for topico in semana['topicos']:
                    plano_formatado += f"""
            <tr>
                <td>{semana['semana']}</td>
                <td>{topico['nome_topico']}</td>
                <td>{topico['duracao_estimada']} horas</td>
                <td><a href="{topico['link_recurso']}">Link</a></td>
            </tr>
            """
            plano_formatado += "</tbody></table>"
        plano_formatado += "</li>\n"
    plano_formatado += """
</ol>
<h3>Conclusão:</h3>
<p>
    Parabéns por concluir este plano de estudos! Você deu um grande passo na sua jornada de aprendizado em Python. Lembre-se que a prática é fundamental.
    Continue praticando, explorando novos projetos e não hesite em buscar ajuda quando precisar. O mundo da programação te espera! Boa sorte e continue aprendendo!
</p>
</div>
"""


    yield status, f"<div style='color: black; background-color: #e0e0e0; max-height: 70vh; overflow-y: auto; padding: 10px; border-radius: 5px; white-space: pre-wrap;'>{plano_formatado}</div>"
    return status, f"<div style='color: black; background-color: #e0e0e0; max-height: 70vh; overflow-y: auto; padding: 10px; border-radius: 5px; white-space: pre-wrap;'>{plano_formatado}</div>"

def clear_output():
    return gr.update(value="")

with gr.Blocks(theme=gr.themes.Base()) as demo: # Adicione o tema aqui
    demo.head = """
        <style>
            #sidebar_column {
                background-color: #d3d3d3;
                padding: 20px;
                border-radius: 5px;
                margin-right: 20px;
                display: flex;
                flex-direction: column;
                align-items: flex-start;
            }
            #logo_container {
                display: flex;
                justify-content: center;
                margin-bottom: 10px;
                width: 100%;
                background-color: #d3d3d3;
                padding: 5px 0;
            }
            #instruction_container {
                text-align: center;
                margin-top: 5px;
                margin-bottom: 15px;
                color: black;
            }
            #output_container {
            }
        </style>
    """
    with gr.Row():
        with gr.Column(scale=1, elem_id="sidebar_column"):
            logo_html = "<div id='logo_container'><img src='https://i.imgur.com/94S9ER5.png' alt='Meu Plano IA Logo' width='200'></div>"
            gr.HTML(logo_html)
            instruction_text = "<div id='instruction_container'>Preencha os campos e clique em 'Gerar Plano' para criar seu roteiro de estudos com IA.</div>"
            gr.HTML(instruction_text)
            objetivo_input = gr.Textbox(label="Objetivo de aprendizado", placeholder="Ex: Aprender a usar o Databricks")
            horas_input = gr.Number(label="Horas semanais disponíveis", precision=0, value=4)
            duracao_input = gr.Textbox(label="Duração total (ex: 2 semanas ou 1 mês)", placeholder="Ex: 3 semanas")
            nivel_input = gr.Radio(choices=["iniciante", "intermediário", "avançado"], label="Nível de conhecimento", value="iniciante")
            recursos_input = gr.Textbox(label="Recursos preferenciais", placeholder="Ex: vídeos, Alura, livros...")
            outras_info_input = gr.Textbox(label="Outras informações relevantes", placeholder="Ex: já estuda à noite, tem dificuldade com leitura...")
            generate_button = gr.Button("Gerar Plano")
            clear_button = gr.Button("Limpar")

        with gr.Column(scale=2):
            gr.Markdown("<h2 style='text-align: center;'>🧠 Meu Plano IA – Gerador de Plano de Estudos com Gemini</h2>")
            status_output = gr.Textbox(label="", show_label=False, interactive=False)
            output_box = gr.HTML(elem_id="output_container")

    generate_button.click(
        fn=gerar_plano_estudos,
        inputs=[objetivo_input, horas_input, duracao_input, nivel_input, recursos_input, outras_info_input],
        outputs=[status_output, output_box]
    )

    clear_button.click(
        fn=clear_output,
        inputs=[],
        outputs=output_box
    )

demo.launch(share=True, debug=False)